### ISSUE TITLE
Object.hasOwn is not a function

### ISSUE THREAD

**Issue by blechatellier** [remarkjs/react-markdown#772]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.0

### Steps to reproduce

I'm using NextJS and after upgrading from v8.0.7 to v9.0.0 I get the following error `Object.hasOwn is not a function` which is not supported by all browsers (chrome v93+), can we keep `hasOwnProperty` instead?

### Expected behavior

It should not throw an error.

### Actual behavior

It throws an Uncaught TypeError `Object.hasOwn is not a function`.

**Comment by blechatellier** [comment]
I have fixed it creating my own polyfill

```
if (!Object.hasOwn) {
  Object.hasOwn = (obj, prop) =>
    Object.prototype.hasOwnProperty.call(obj, prop);
}
```

**Comment by ChristianMurphy** [comment]
Welcome @blechatellier! 👋 
Sorry you ran into a spot of trouble.

`react-markdown` targets the V8 runtime of Node's long term release.
Currently Node 16, with support for ECMA2022, at the time of writing.

If you'd like to support older runtimes, either in browser or in node.
Use `@babel/preset-env` to transpile syntax features and polyfill globals to match the specific environment you need to support.

The intent of `react-markdown` is to offer a fast, modern, idiomatic library.
Allowing adopters to transpile and polyfill only what is needed on their project, rather than forcing transpilation and polyfills on all several million projects leveraging `react-markdown`, most of whom do not need most, if any, of them.

Feel free to reach out in discussions if you have questions or concerns https://github.com/orgs/remarkjs/discussions

**Comment by blechatellier** [comment]
Thanks for taking the time to reply @ChristianMurphy completely understand keeping support current.
