### ISSUE TITLE
ERROR this.getData is not a function TypeError: this.getData is not a function

### ISSUE THREAD

**Issue by Surya-Kanta** [remarkjs/react-markdown#794]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.0

### Steps to reproduce

```
<Markdown
    rehypePlugins={[remarkGfm, rehypeRaw]}
>
    {modified_content}
</Markdown>
```

### Expected behavior

The code should be able to work properly.
Earlier it was working and still it is working with version 8.0.7

### Actual behavior

```
ERROR
this.getData is not a function
TypeError: this.getData is not a function
    at Object.exitCodeText (http://localhost:3000/static/js/bundle.js:103717:12)
    at compile (http://localhost:3000/static/js/bundle.js:121979:40)
    at fromMarkdown (http://localhost:3000/static/js/bundle.js:121821:27)
    at parser (http://localhost:3000/static/js/bundle.js:121609:82)
    at Function.parse (http://localhost:3000/static/js/bundle.js:118228:12)
    at Markdown (http://localhost:3000/static/js/bundle.js:116580:31)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:49888:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:53174:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:54470:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:39480:18)
```

### Runtime

Node v17

### Package manager

npm 8

### OS

Linux

**Comment by JounQin** [comment]
> Link to runnable example
> No response

Please fill the section, a runnable reproduction is required to help us debugging.

**Comment by wooorm** [comment]
And search for issues. This has been asked before. Update *all* your dependencies.

**Comment by oeyoews** [comment]
This is a problem with the remarkgfm plugin, but I have not seen similar problems in the issue

**Comment by wooorm** [comment]
It is a problem when some old projects are used with new projects.
All new versions are published.
Update.
